export const categories = [
  { id: "all", label: "Todos" },
  { id: "garcom", label: "Garçom" },
  { id: "barman", label: "Barman" },
  { id: "chef", label: "Chef" },
  { id: "limpeza", label: "Limpeza" },
];

export const turns = [
  {
    id: "1",
    category: "garcom",
    title: "Garçom para Evento",
    place: "Restaurante Fino Trato",
    location: "Pinheiros, SP",
    distance: "2.4 km de você",
    time: "Hoje, 18:00 - 22:00",
    hours: "4h totais",
    paymentType: "Por hora",
    price: "R$ 80/h",
    total: "TOTAL R$ 320",
    image:
      "https://images.unsplash.com/photo-1528605248644-14dd04022da1",
  },
  {
    id: "2",
    category: "barman",
    title: "Barman para Festa",
    place: "Espaço Vila Lobos",
    location: "Alto de Pinheiros, SP",
    distance: "4.1 km de você",
    time: "Sábado, 20:00 - 02:00",
    hours: "6h totais",
    paymentType: "Por turno",
    price: "R$ 450",
    total: "PAGAMENTO ÚNICO",
    image:
      "https://images.unsplash.com/photo-1626861932509-c1e7eb62c6c1?q=80&w=1175&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    id: "3",
    category: "chef",
    title: "Chef para Evento Privado",
    place: "Residência Particular",
    location: "Moema, SP",
    distance: "6.8 km de você",
    time: "Domingo, 12:00 - 18:00",
    hours: "6h totais",
    paymentType: "Diária",
    price: "R$ 1.200",
    total: "DIÁRIA",
    image:
      "https://images.unsplash.com/photo-1551218808-94e220e084d2",
  },
  {
    id: "4",
    category: "limpeza",
    title: "Auxiliar de Limpeza",
    place: "Centro de Eventos São Paulo",
    location: "Barra Funda, SP",
    distance: "3.2 km de você",
    time: "Hoje, 08:00 - 14:00",
    hours: "6h totais",
    paymentType: "Por hora",
    price: "R$ 45/h",
    total: "TOTAL R$ 270",
    image:
      "https://images.unsplash.com/photo-1581578731548-c64695cc6952",
  },
  {
    id: "5",
    category: "garcom",
    title: "Garçom para Restaurante",
    place: "Bistrô Urbano",
    location: "Vila Madalena, SP",
    distance: "1.1 km de você",
    time: "Hoje, 18:30 - 23:30",
    hours: "5h totais",
    paymentType: "Por hora",
    price: "R$ 75/h",
    total: "TOTAL R$ 375",
    image:
      "https://images.unsplash.com/photo-1516788875874-c5912cae7b43?q=80&w=1173&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
];
